# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# For your production deployments, you probably want to run CI on ALL branches.
# You may have separate CI (lighter-weight) processes for your Dev/* builds...

trigger:
- main

variables:
- name: _filePath
  value: '$(Build.SourcesDirectory)/deploy/'
- name: _fileName
  value: 'main'

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build_Bicep
    steps:

    - task: PowerShell@2
      displayName: 'Build the ARM Template from the BICEP file'
      inputs:
        targetType: 'inline'
        script: 'az bicep build --file ${{ variables._filePath }}${{ variables._fileName }}.bicep'

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        connectedServiceName: 'azure_service_connection'
        location: $(deploymentDefaultLocation)
        deploymentMode: Validation
        resourceGroupName: 'iac-demo-ado-nonprod-rg'
        csmFile: ${{ variables._filePath }}${{ variables._fileName }}.bicep

    - task: CopyFiles@2
      displayName: 'Copy ARM Template files to Staging directory'
      inputs:
        SourceFolder: '${{ variables._filePath }}'
        Contents: '${{ variables._fileName }}.bicep'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/templates'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ARM Templates'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/templates'
        ArtifactName: 'templates'
